### ISSUE TITLE
Congrats and suggestion

### ISSUE THREAD

**Issue by juanestebanj** [rudikershaw/whichx#1]
Hello

I was glad to see that I was able to have a good outcome from your library to solve a classification problem at work.
I actually noticed that your library worked better than https://github.com/ttezel/bayes (about 400 stars) with the same training data.
So I would recommend that you make available by a better name your Naive Bayes code, so that more people can find it (and benefit from it) beyond the pets domain.

Congrats!

**Comment by rudikershaw** [comment]
Hi @juanestebanj 

I am glad you've found it useful. It is always good to hear when your work is appreciated.

I'm quite attached to the name 'Whichpet', but I have added more topics to the repository to help it show higher in the listings. If you search for 'Naive bayes text classifier' and filter 'JavaScript' it is now showing fourth from the top.

Thank you for your comments and suggestions.
