### ISSUE TITLE
Minify deliverable

### ISSUE THREAD

**Issue by rudikershaw** [rudikershaw/whichx#13]
One of the value adds of this classification library is that it is really really small. It's worth taking that one step further and making it as small as it can be. 

* Add some kind of minify to the build.
* Ensure the minified version is published for new versions.
* Ensure that the project JSDoc is still displayed in the IDE of a project using whichx as a dependency.
* Add checks to ensure deliverable stays below a certain size to protect against bloat.

**Comment by Sharcoux** [comment]
About minification. I actually think that this is a mistake. Most projects will use webpack or other tools to minify the dependencies and will generate a source map for them. With minified version, debugging this lib might be annoying.

Here is my advice:

- Or you should generate a minified version with it's source map
- Or you should let the users handle minification with webpack

**Comment by rudikershaw** [comment]
For posterity, minification was added as part of PR #17.

**Comment by rudikershaw** [comment]
With the exception of limiting the deliverable size in the build, all the other changes have been made. I will raise a follow up issue for validating the index.js deliverable file size.
